# Spring Properties
spring:
  application:
     name: service01
# Discovery Server Access
eureka:
  client:
     serviceUrl:
      defaultZone: http://localhost:1111/eureka/ 
  instance:
        preferIpAddress: true
        metadataMap:
            instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        leaseRenewalIntervalInSeconds: 1000
        leaseExpirationDurationInSeconds: 2000
 # HTTP Server
server:
  port: 8082  
    